apiVersion: v1
kind: ReplicationController
metadata:
  name: enforcer-edge-v0.0.1
  labels:
    name: enforcer
    env: edge
    version: 0.0.1
spec:
  replicas: 3
  selector:
    name: enforcer
    env: edge
    version: 0.0.1
  template:
    metadata:
      labels:
        name: enforcer
        env: edge
        version: 0.0.1
    spec:
      containers:
        - name: mouth
          image: eu.gcr.io/gi-harbour/enforcer:0.0.1
          ports:
            - containerPort: 9090
              protocol: TCP
