apiVersion: v1
kind: ReplicationController
metadata:
  name: enforcer-v0.0.3
  labels:
    name: enforcer
    env: prod
    version: 0.0.3
spec:
  replicas: 3
  selector:
    name: enforcer
    env: prod
    version: 0.0.3
  template:
    metadata:
      labels:
        name: enforcer
        env: prod
        version: 0.0.3
    spec:
      containers:
        - name: mouth
          image: eu.gcr.io/gi-harbour/enforcer:0.0.3
          ports:
            - containerPort: 9090
              protocol: TCP
