apiVersion: v1
kind: Service
metadata:
  name: enforcer
  labels:
    name: enforcer
    env: prod
    version: 0.0.1
spec:
  ports:
    - port: 80
      targetPort: 9090
      nodePort: 31083
      protocol: TCP
      name: http
  selector:
    name: enforcer
    env: prod
